flag_data = [
    (197, "shady_guy"),
    (177, "pendant_courage"),
    (249, "pendant_wisdom"),
    (289, "pendant_power"),
    (437, "portrait_gulley"),
    (473, "portrait_oren"),
    (505, "portrait_seres"),
    (529, "portrait_osfala"),
    (557, "portrait_rosso"),
    (581, "portrait_irene"),
    (617, "portrait_impa"),
    (801, "crack_stylish_woman"),
    (802, "crack_your_house"),
    (803, "crack_paradox_lower_hyrule"),
    (804, "crack_paradox_upper_hyrule"),
    (805, "crack_waterfall_hyrule"),
    (806, "crack_eastern_ruins_pillar"),
    (807, "crack_eastern_ruins_se"),
    (808, "crack_lost_woods"),
    (809, "crack_sahasrahlas_house"),
    (810, "crack_rossos_house"),
    (811, "crack_to_misery_mire"),
    (812, "crack_desert_pillar_right"),
    (813, "crack_desert_pillar_left"),
    (814, "crack_desert_middle"),
    (815, "crack_desert_sw"),
    (816, "crack_to_zaganaga"),
    (817, "crack_desert_north"),
    (818, "crack_dm_west_hyrule"),
    (819, "crack_rossos_ore_mine_hyrule"),
    (820, "crack_river_hyrule"),
    (821, "crack_lake_hylia"),
    (822, "crack_hyrule_hotfoot"),
    (823, "crack_sanctuary"),
    (824, "crack_graveyard_ledge_hyrule"),
    (825, "crack_floating_island_hyrule"),
    (826, "crack_swamp_pillar_hyrule"),
    (827, "crack_zoras_domain"),
    (831, "crack_thieves_town"),
    (832, "crack_vacant_house"),
    (833, "crack_paradox_upper_lorule"),
    (834, "crack_paradox_lower_lorule"),
    (835, "crack_waterfall_lorule"),
    (836, "crack_dark_ruins_pillar"),
    (837, "crack_dark_maze_se"),
    (838, "crack_skull_woods_pillar"),
    (839, "crack_n_shaped_house"),
    (840, "crack_destroyed_house"),
    (841, "crack_misery_mire_exit"),
    (842, "crack_mire_pillar_right"),
    (843, "crack_mire_pillar_left"),
    (844, "crack_mire_middle"),
    (845, "crack_mire_sw"),
    (846, "crack_zaganaga_exit"),
    (847, "crack_mire_north"),
    (848, "crack_dm_west_lorule"),
    (849, "crack_rossos_ore_mine_lorule"),
    (850, "crack_river_lorule"),
    (851, "crack_lorule_lake_west"),
    (852, "crack_lorule_coldfoot"),
    (853, "crack_philosophers_cave"),
    (854, "crack_graveyard_ledge_lorule"),
    (855, "crack_floating_island_lorule"),
    (856, "crack_swamp_pillar_lorule"),
    (857, "crack_kus_domain"),
    (920, "vane_your_house"),
    (921, "vane_kakariko_village"),
    (922, "vane_eastern_palace"),
    (923, "vane_house_of_gales"),
    (924, "vane_tower_of_hera"),
    (925, "vane_witchs_house"),
    (926, "vane_death_mtn_hyrule"),
    (927, "vane_desert_palace"),
    (928, "vane_sanctuary"),
    (932, "vane_skull_woods"),
    (933, "vane_treacherous_tower"),
    (934, "vane_ice_ruins"),
    (935, "vane_lorule_castle"),
    (936, "vane_graveyard"),
    (937, "vane_thieves_town"),
    (938, "vane_dark_palace"),
    (939, "vane_blacksmith"),
    (940, "vane_vacant_house"),
    (941, "vane_misery_mire"),
    (942, "vane_swamp_palace"),
    (943, "vane_turtle_rock"),
    (944, "vane_death_mtn_lorule"),
]

nice_items = [
    (2, "nice_bombs"),
    (3, "nice_boomerang"),
    (4, "nice_bow"),
    (6, "nice_hammer"),
    (7, "nice_sand_rod"),
    (8, "nice_fire_rod"),
    (9, "nice_ice_rod"),
    (10, "nice_tornado_rod"),
    (11, "nice_hookshot"),
]

scoot_fruit_flag = "scoot_fruit"
golden_bee_flag = "golden_bee"

# (message label, course, name) of each hint ghost, in the order the patcher assigns hints to them;
# courses 0/1/3 are FieldLight/FieldDark/IndoorDark, the last entry is the Bow of Light ghost;
# a visited ghost is stored as flag ghost_<name> for trackers
hint_ghost_labels = [
    ("lgt_MayoinoHintObake_Msg4", 0, "lost_woods_maze_1"),
    ("lgt_MayoinoHintObake_Msg8", 0, "lost_woods_maze_2"),
    ("lgt_MayoinoHintObake_Msg6", 0, "lost_woods_maze_3"),
    ("HintGhost_FieldLight_00_000", 0, "lost_woods"),
    ("HintGhost_FieldLight_03_002", 0, "spectacle_rock"),
    ("HintGhost_FieldLight_03_003", 0, "tower_of_hera_outside"),
    ("HintGhost_FieldLight_05_004", 0, "floating_island"),
    ("HintGhost_FieldLight_05_005", 0, "fire_cave"),
    ("HintGhost_FieldLight_0A_006", 0, "moldorm_cave"),
    ("HintGhost_FieldLight_0F_007", 0, "zoras_domain"),
    ("HintGhost_FieldLight_11_008", 0, "fortune_teller_hyrule"),
    ("HintGhost_FieldLight_13_009", 0, "sanctuary"),
    ("HintGhost_FieldLight_14_010", 0, "graveyard_hyrule"),
    ("HintGhost_FieldLight_17_011", 0, "waterfall_cave"),
    ("HintGhost_FieldLight_18_012", 0, "well"),
    ("HintGhost_FieldLight_18_013", 0, "shady_guy"),
    ("HintGhost_FieldLight_18_014", 0, "stylish_woman"),
    ("HintGhost_FieldLight_22_015", 0, "blacksmith_cave"),
    ("HintGhost_FieldLight_1E_016", 0, "eastern_ruins_pegs"),
    ("HintGhost_FieldLight_1E_017", 0, "eastern_ruins_cave"),
    ("HintGhost_FieldLight_1E_018", 0, "eastern_ruins_entrance"),
    ("HintGhost_FieldLight_28_019", 0, "rupee_rush_hyrule"),
    ("HintGhost_FieldLight_29_020", 0, "cuccos"),
    ("HintGhost_FieldLight_2D_021", 0, "south_bridge"),
    ("HintGhost_FieldLight_33_022", 0, "southern_ruins"),
    ("HintGhost_FieldLight_35_023", 0, "house_of_gales_island"),
    ("HintGhost_FieldLight_37_024", 0, "hyrule_hotfoot"),
    ("HintGhost_FieldLight_37_025", 0, "letter"),
    ("HintGhost_FieldLight_2B_026", 0, "streetpass_tree"),
    ("HintGhost_FieldLight_1A_027", 0, "blacksmith_behind"),
    ("HintGhost_FieldLight_14_028", 0, "graveyard_ledge"),
    ("HintGhost_FieldLight_14_029", 0, "desert_east"),
    ("HintGhost_FieldLight_14_030", 0, "desert_center"),
    ("HintGhost_FieldLight_14_031", 0, "desert_southwest"),
    ("HintGhost_FieldLight_14_032", 0, "hyrule_castle_rocks"),
    ("HintGhost_FieldLight_14_033", 0, "witchs_house"),
    ("HintGhost_FieldDark_02_001", 1, "skull_woods_cuccos"),
    ("HintGhost_FieldDark_03_002", 1, "treacherous_tower"),
    ("HintGhost_FieldDark_07_003", 1, "ice_ruins_outside"),
    ("HintGhost_FieldDark_14_004", 1, "lorule_graveyard"),
    ("HintGhost_FieldDark_16_005", 1, "dark_ruins_north"),
    ("HintGhost_FieldDark_18_006", 1, "skull_woods_south"),
    ("HintGhost_FieldDark_18_007", 3, "fortunes_choice"),
    ("HintGhost_FieldDark_18_008", 3, "veteran_thief"),
    ("HintGhost_FieldDark_1A_009", 1, "fortune_teller_lorule"),
    ("HintGhost_FieldDark_1E_010", 1, "dark_maze"),
    ("HintGhost_FieldDark_28_011", 1, "rupee_rush_lorule"),
    ("HintGhost_FieldDark_29_012", 1, "great_rupee_fairy"),
    ("HintGhost_FieldDark_2A_013", 1, "octoball_derby"),
    ("HintGhost_FieldDark_2C_014", 1, "vacant_house"),
    ("HintGhost_FieldDark_30_015", 1, "misery_mire_ledge"),
    ("HintGhost_FieldDark_33_016", 1, "swamp_palace_outside_left"),
    ("HintGhost_FieldDark_35_017", 1, "turtle_bullied"),
    ("HintGhost_FieldDark_35_018", 1, "turtle_wall"),
    ("HintGhost_FieldDark_35_019", 1, "turtle_rock_outside"),
    ("HintGhost_FieldDark_1E_020", 1, "dark_palace_outside"),
    ("HintGhost_FieldDark_33_021", 1, "swamp_palace_outside_right"),
    ("HintGhost_FieldDark_33_022", 1, "misery_mire_bridge"),
    ("HintGhost_FieldDark_2C_014", 3, "bow_of_light"),
]
